@startuml overview
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_TOP_DOWN

Person(practitioner, "Practitioner", "Professional providing Health Certificates")
Person(citizen, "Citizen", "The user holding Health Certificates")
Person(otherPerson, "Other person", "A person/professional checking Health Certificate")
SystemDb(healthAuthority, "Health Authority", "Health authority managing pandemia")

Rel(citizen, healthAuthority, "Provides some information to", "VC with Consent")

Rel_R(practitioner, citizen, "Issues Health credential", "Digitally signed")
Rel_R(citizen, otherPerson, "Shows credential to", "With Consent")

@enduml

@startuml practitioner

hide stereotype
skinparam ActorBorderColor<< Pract >> Blue
skinparam ActorBackgroundColor<< Pract >> Blue

skinparam ActorBorderColor<< Citi >> Black

actor Practitioner<< Pract >>
file Credential as "Verifiable\nCredential"

actor Citizen<< Citi>>

Practitioner - Credential
Credential -> Citizen

@enduml

@startuml official

hide stereotype
skinparam ActorBorderColor<< Offic >> Red
skinparam ActorBackgroundColor<< Offic >> Red

skinparam ActorBorderColor<< Citi >> Black

actor Official<< Offic >>
file Credential as "Verifiable\nCredential"

actor Citizen<< Citi>>

Citizen - Credential
Credential -> Official

@enduml

@startuml questionnaire
salt
{^
  <b>Questionnaire
  [X] Breathing
  [X] Fever
  [X] Cough
===|===
[ Cancel ] | [  OK   ]
}
@enduml

@startsalt consent
{^
<b>Consent to 
<b>use GPS
===========|==========
[ Cancel ] | [  OK   ]
}
@endsalt
