@startuml display_credential

autonumber
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam maxmessagesize 150

box "User" #LightCyan
  actor User as U
  participant "Mobile" as MU
end box

box "Other person" #LightCyan
  participant "Mobile" as MP
  actor Person as P
end box

box "EBSI registry" #LightCyan
  Collections "Public Node" as BR
end box

== Send credential as QR ==
MU -> MP: Display credential as QR
note over MU, MP #white
    <img:https://raw.githubusercontent.com/hesusruiz/anti-pandemia/master/docs/images/qrcode.png {scale=0.2}> 
end note

MP -> MP: Scan Credential

P -[hidden]> BR: This is hidden and used for separation

== Validate credential ==
MP -> BR: Validate practitioner signature

MP -> P: Display credential data

@enduml