@startuml receive_credential

autonumber
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam maxmessagesize 150

box "User" #LightCyan
  actor User as U
  participant "Mobile" as MU
end box

box "Practitioner" #LightCyan
  participant "Mobile" as MP
  actor Practitioner as P
end box

== Creation of Disposable Credential ==
U -> MU: Asks create Disposable Credential
MU -> MU: Derives Disposable DID from normal DID

MU -> MU: Get name, address, mobile, ...
MU -> MU: Create Disposable Credential

== Send credential as QR ==
MU -> MP: Display credential as QR
note over MU, MP #white
    <img:https://gitlab.com/hesusruiz/anti-pandemia/-/raw/master/qrcode.png {scale=0.2}> 
end note

MP -> MP: Scan Credential

== Validate personal data ==
MP -> P: Display citizen data
P -> MP: Confirm citizen data

== Create Health Status credential ==
MP -> P: Ask for Health Status
P -> MP: Input health data and confirm
MP -> MP: Generate Health Status credential

== Send credential as QR ==
MP -> MU: Display credential as QR
note over MU, MP #white
    <img:https://gitlab.com/hesusruiz/anti-pandemia/-/raw/master/qrcode.png {scale=0.2}> 
end note

MU -> MU: Scan Health credential

== Validate and store Health credential in mobile ==
MU -> U: Display Health credential data
U -> MU: Confirm

MU -> MU: Store Health credential encrypted
MU -> U: Display confirmation

@enduml