@startuml citizen

autonumber
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam maxmessagesize 150

box "User" #LightCyan
actor User as U
participant "Mobile" as M
end box

U -> M: Download App

== Creation of DID ==
M -> U: Ask to generate DID
U -> M: Confirm
M -> M: Generate Private+Public keys
M -> M: Generate DID from keys

== Ask for personal data ==
M -> U: Ask for personal data & consent
U -> M: Provide name, address, mobile, ...

== Ask for GPS data ==
M -> U: Ask consent for GPS data
U -> M: Give consent (or not)

== Self-issue credential ==
M -> M: Create credential with personal data and consent
M -> M: Sign credential with private key
M -> U: Ask for new password
U -> M: Provide new password (optionally fingerprint)
M -> M: Store data locally encrypted

@enduml